baseurl = "http://itsmrn.com"
languageCode = "en-us"
title = "Narsi Reddy"
theme = "beautifulhugo"
pygmentsUseClasses = true

[Params]
  subtitle = "PhD Student at UMKC"
  logo = "img/avatar-icon.jpg"
  favicon = "img/favicon.ico"
  commit = false

[Author]
  name = "narsi reddy, donthi reddy"
  email = "sainarsireddy@hotmail.com"
  facebook = "sainarsi.reddy"
  github = "itsnarsi"
  twitter = "itsnarsi"
  linkedin = "/in/sai-narsi-reddy-donthi-reddy-0b346536"
  stackoverflow = ""
  soundcloud = ""
  wikipedia = ""

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1


[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 2

